[functions.mission-engine]
verify_jwt = true
import_map = "./import_map.json"

[functions.reward-distribution]
verify_jwt = true
import_map = "./import_map.json"

[functions.submission-engine]
verify_jwt = true
import_map = "./import_map.json"

[functions.vote-engine]
verify_jwt = true
import_map = "./import_map.json"

[functions.ai-verification-receiver]
verify_jwt = false
import_map = "./import_map.json"

[functions.weather-ingestion]
verify_jwt = false
import_map = "./import_map.json"

[functions.ai-engine]
verify_jwt = false
import_map = "./import_map.json"

[functions.weather-fetcher]
verify_jwt = false
import_map = "./import_map.json"
